name: neo_player
description: Audio player app build with flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ################################ UI PACKAGES #################################

  # Icons for IOS
  cupertino_icons: ^1.0.2

  # Showcase/Highlight widgets step by step.
  showcaseview: ^1.1.6

  # A flutter package to allow drag-and-drop reordering of two-level lists.
  drag_and_drop_lists: ^0.3.2+2

  # mini player
  miniplayer: ^1.0.1

  # A Flutter implementation of sticky headers with a sliver as a child.
  flutter_sticky_header: ^0.6.3

  # Neumorphic ui kit for Flutter.
  flutter_neumorphic: ^3.2.0

  # Easy and Fast internationalizing and localization.
  easy_localization: ^3.0.1

  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0

  # An SVG rendering
  flutter_svg: ^1.1.0

  # Toast Library for Flutter
  fluttertoast: ^8.0.9

  # Loading indicators animated
  flutter_spinkit: ^5.1.0

  # Easily add staggered animations to your ListView, GridView, Column
  flutter_staggered_animations: ^1.0.0

  # A progress bar widget to show or change the position of an audio or video stream.
  # https://suragch.medium.com/steaming-audio-in-flutter-with-just-audio-7435fcf672bf
  # https://suragch.medium.com/managing-playlists-in-flutter-with-just-audio-c4b8f2af12eb
  audio_video_progress_bar: ^0.10.0

  # pre-canned animations for commonly-desired effects
  animations: ^2.0.3

  # Powerful package to create beautiful custom animations in no time.
  simple_animations: ^4.2.0

  ########################## DATA PERSISTENCE PACKAGES #########################

  # Flutter plugin for reading and writing simple key-value pairs.
  shared_preferences: ^2.0.15

  # Adds SQLite support with Data Access Objects and streams
  sqflite: ^2.0.2+1

  # Fast, Enjoyable & Secure NoSQL Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  ############################### OTHER PACKAGES ###############################

  # A feature-rich audio player
  just_audio: ^0.9.27
  # just_audio_background: ^0.0.1-beta.7

  # query audios/songs ðŸŽ¶ from device storage.
  on_audio_query: ^2.6.1

  # Create a room to storage audio sections
  on_audio_room: ^2.2.1+1

  # To play audio in the background while the screen is off.
  # audio_service: ^0.18.6
  audio_session: ^0.1.8

  # Supplies the app with the directory location for storing files
  path_provider: ^2.0.11
  provider: ^6.0.3
  path: ^1.8.0

  # A simple yet powerful state management technique for Flutter.
  states_rebuilder: ^6.1.0+1

  # Querying information about an application package.
  package_info_plus: ^1.4.2

  # Sharing content via the platform share UI,
  share_plus: ^4.0.10

  # Get current device information
  device_info_plus: ^4.0.0

  # A Flutter plugin for launching a URL
  url_launcher: ^6.1.4

  # Permission plugin for Flutter.
  permission_handler: ^9.2.0

  # Service Locator
  get_it: ^7.2.0

  # RxDart is an implementation of the popular reactiveX api for asynchronous
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Defines files available to the app
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/locales/
    - assets/google_fonts/

  # Specifies fonts and their respective font weights (thickness)
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/google_fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Nunito-Black.ttf
          weight: 900